#!/bin/sh

TAR_GZ="SoapUI-5.4.0-EB-linux-bin.tar.gz"

tar -xf "$HOME/$TAR_GZ" -C /opt/soapui/ --strip-components=1

chmod a+r -R /opt/soapui
find /opt/soapui/ -type d -exec chmod a+x {} \;
find /opt/soapui/ -type f -name *sh -exec chmod a+x {} \;
